AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
